from pathlib import Path
import shutil,json,hashlib
r=Path('/home/gama/sgx535-gfx');w=Path(__file__).parent
e=r/'docs/phase8/artifacts/experimental-first-load-01-20261001';e.mkdir()
for name in ['initial-pwd.txt','initial-status.txt','initial-files.json','corrected-inputs.json','build-commands.json','corrected-build-commands.json','run_build.py','run_corrected_build.py','verify_corrected_repeat.py','verified-corrected-repeat.json','verified-corrected-repeat.stdout','corrected-repeat-build.json','repeat-build.json','inputs.json','corrected-build.stdout','corrected-build.stderr','corrected-inspection.stdout','corrected-inspection.stderr','run_negative_images.py','negative-images.stdout','negative-images.stderr','metadata-review-red.stdout','metadata-review-red.stderr','irq-review-red.stdout','irq-review-red.stderr','review-fixes-green.stdout','review-fixes-green.stderr','final-focused.stdout','final-focused.stderr','run_final_guards.py','final-guards.stdout','final-guards.stderr','pre-review-hook.sh.in']:
 p=w/name
 if p.exists():shutil.copy2(p,e/name)
for directory in ['build-03','independent-inspection-corrected','final-checks']:
 shutil.copytree(w/directory,e/directory)
(e/'negative-images').mkdir();shutil.copy2(w/'negative-images/results.json',e/'negative-images/results.json')
(e/'preserved-superseded-builds.json').write_text(json.dumps({'classification':'SUPERSEDED, NOT QUALIFIED FOR FUTURE STAGING','pre_review_images':[{'path':str(w/f'build-0{n}/initrd.img-sgx535-firstload-01'),'sha256':hashlib.sha256((w/f'build-0{n}/initrd.img-sgx535-firstload-01').read_bytes()).hexdigest()} for n in [1,2]],'pre_review_inspection':str(w/'independent-inspection'),'incorrect_repeat_record':'corrected-repeat-build.json read old images; superseded by verified-corrected-repeat.json which reads actual corrected build03/04; scripts/logs preserved unchanged','negative_image_bytes_remain_off_repository':str(w/'negative-images'),'corrected_repeat_image':str(w/'build-04/initrd.img-sgx535-firstload-01')},indent=2)+'\n')
(e/'review-resolution.json').write_text(json.dumps({'reviewer':'first_load_image_review','critical':0,'important':[{'finding':'post-load handler not tied to PCI IRQ16','resolution':'Separate any-line stale-handler predicate before load and exact IRQ16 predicate after load; actual helpers and emitted hook tested','test_evidence':'metadata-review-red.stderr / final-focused.stderr'},{'finding':'verifier could accept nonexecutable init or colliding/hardlinked added records','resolution':'validate retained init metadata and deterministic disjoint new inode/type/mode/nlink/dev/owner/mtime records; actual-image mutations rejected','test_evidence':'metadata-review-red.stderr / negative-images/results.json'}],'new_review_required':False,'no_target_contact':True},indent=2)+'\n')
print(e)
