#ifndef SGX535_FROZEN_FIXED_SERVICE_H
#define SGX535_FROZEN_FIXED_SERVICE_H

#include "frozen_kernel_contract.h"

/* This is a single-scene internal call sequence. The callback is not a
 * userspace ABI or a qualified hardware implementation. Each stage receives
 * only data generated by the fixed contract. */
enum sgx535_fixed_stage {
    SGX535_FIXED_PUBLISH_CPU = 1,
    SGX535_FIXED_PUBLISH_TRANSLATIONS,
    SGX535_FIXED_DEVICE_MAINTAIN,
    SGX535_FIXED_INIT_WRITES,
    SGX535_FIXED_XHW_INIT,
    SGX535_FIXED_TA_INFO,
    SGX535_FIXED_SCENE_INFO,
    SGX535_FIXED_TA_LOAD,
    SGX535_FIXED_SCENE_VALIDATE,
    SGX535_FIXED_USE_RESERVE,
    SGX535_FIXED_USE_PROGRAM,
    SGX535_FIXED_STATUS_BASELINE,
    SGX535_FIXED_TA_SCHEDULE,
    SGX535_FIXED_TA_FIRE,
    SGX535_FIXED_ISP_RESET_ASSERT,
    SGX535_FIXED_ISP_RESET_CLEAR,
    SGX535_FIXED_RASTER_SCHEDULE,
    SGX535_FIXED_RASTER_FIRE,
    SGX535_FIXED_USE_RELEASE
};

struct sgx535_fixed_observation {
    sgx535_u32 load_flags;
    sgx535_u32 status1;
    sgx535_u32 status2;
    sgx535_u32 initend;
};

/* Internal fire payload: the fixed wire image and its selected Xpsb device
 * action path travel together. A backend must not derive new operations from
 * user input or treat the wire image alone as the executable service. */
struct sgx535_fixed_fire_payload {
    struct sgx535_frozen_xhw_bind_fire_wire wire;
    struct sgx535_frozen_reg_action actions[31];
    sgx535_u32 action_count;
};

struct sgx535_fixed_ops {
    int (*run)(void *context, enum sgx535_fixed_stage stage,
               const void *payload, size_t count,
               struct sgx535_fixed_observation *observation);
};

/* A future live source must atomically associate and acknowledge selected
 * status for this scene. A raw register snapshot alone is not attribution. */
struct sgx535_fixed_status_source {
    int (*sample_and_ack)(void *context, sgx535_u32 sequence,
                          sgx535_u32 *status1, sgx535_u32 *status2,
                          int *exclusive_owned);
};

struct sgx535_fixed_service {
    struct sgx535_frozen_session *session;
    struct sgx535_frozen_bo bos[SGX535_BO_COUNT];
    struct sgx535_frozen_command_pairs commands;
    struct sgx535_frozen_xhw_bind_fire_wire ta_wire;
    struct sgx535_frozen_xhw_bind_fire_wire raster_wire;
    struct sgx535_frozen_use_plan use_plan;
    struct sgx535_frozen_bootstrap boot;
    sgx535_u64 mmu_end;
    sgx535_u32 started;
    sgx535_u32 unsafe_possible;
    sgx535_u32 use_owned;
};

int sgx535_fixed_service_bind(struct sgx535_fixed_service *service,
                              struct sgx535_frozen_session *session,
                              const struct sgx535_frozen_bo *bos,
                              size_t count, sgx535_u64 mmu_end,
                              const struct sgx535_frozen_command_pairs *commands);
int sgx535_fixed_service_prepare(struct sgx535_fixed_service *service,
                                  const struct sgx535_fixed_ops *ops,
                                  void *context, sgx535_u32 raw_revision);
int sgx535_fixed_service_fire_ta(struct sgx535_fixed_service *service,
                                  const struct sgx535_fixed_ops *ops,
                                  void *context, sgx535_u32 sequence,
                                  sgx535_u32 timeout_ticks);
int sgx535_fixed_service_status(struct sgx535_fixed_service *service,
                                 const struct sgx535_fixed_ops *ops,
                                 void *context, sgx535_u32 sequence,
                                 sgx535_u32 status1, sgx535_u32 status2,
                                 int exclusive_owned);
int sgx535_fixed_service_timeout(struct sgx535_fixed_service *service);
int sgx535_fixed_service_retire(struct sgx535_fixed_service *service,
                                 const struct sgx535_fixed_ops *ops,
                                 void *context);
int sgx535_fixed_service_may_release(
    const struct sgx535_fixed_service *service);
int sgx535_fixed_service_run_once(
    struct sgx535_fixed_service *service,
    const struct sgx535_fixed_ops *ops,
    const struct sgx535_fixed_status_source *source,
    void *context, sgx535_u32 raw_revision,
    sgx535_u32 sequence, sgx535_u32 timeout_ticks,
    sgx535_u32 max_samples);

#endif
