#ifndef SGX535_FROZEN_FIXED_SERVICE_H
#define SGX535_FROZEN_FIXED_SERVICE_H

#include "frozen_kernel_contract.h"

/* This is a single-scene internal call sequence. The callback is not a
 * userspace ABI or a qualified hardware implementation. Each stage receives
 * only data generated by the fixed contract. */
enum sgx535_fixed_stage {
    SGX535_FIXED_STAGE_NONE = 0,
    SGX535_FIXED_PUBLISH_CPU = 1,
    SGX535_FIXED_PUBLISH_TRANSLATIONS,
    SGX535_FIXED_DEVICE_MAINTAIN,
    SGX535_FIXED_INIT_WRITES,
    SGX535_FIXED_XHW_INIT,
    SGX535_FIXED_TA_INFO,
    SGX535_FIXED_SCENE_INFO,
    SGX535_FIXED_TA_LOAD,
    SGX535_FIXED_SCENE_VALIDATE,
    SGX535_FIXED_USE_RESERVE,
    SGX535_FIXED_USE_PROGRAM,
    SGX535_FIXED_STATUS_BASELINE,
    SGX535_FIXED_TA_SCHEDULE,
    SGX535_FIXED_TA_FIRE,
    SGX535_FIXED_ISP_RESET_ASSERT,
    SGX535_FIXED_ISP_RESET_CLEAR,
    SGX535_FIXED_RASTER_SCHEDULE,
    SGX535_FIXED_RASTER_FIRE,
    SGX535_FIXED_USE_RELEASE,
    /* Trace labels only: these are not passed to the hardware backend. */
    SGX535_FIXED_STATUS_SAMPLE,
    SGX535_FIXED_STATUS_PROCESS,
    SGX535_FIXED_TIMEOUT
};

enum sgx535_fixed_failure_source {
    SGX535_FIXED_FAILURE_NONE = 0,
    SGX535_FIXED_FAILURE_BACKEND_CALLBACK,
    SGX535_FIXED_FAILURE_STATUS_SOURCE,
    SGX535_FIXED_FAILURE_SERVICE_CHECK,
    SGX535_FIXED_FAILURE_TIMEOUT
};

struct sgx535_fixed_observation {
    sgx535_u32 load_flags;
    sgx535_u32 status1;
    sgx535_u32 status2;
    sgx535_u32 initend;
};

/* Internal fire payload: the fixed wire image and its selected Xpsb device
 * action path travel together. A backend must not derive new operations from
 * user input or treat the wire image alone as the executable service. */
struct sgx535_fixed_fire_payload {
    struct sgx535_frozen_xhw_bind_fire_wire wire;
    struct sgx535_frozen_reg_action actions[31];
    sgx535_u32 action_count;
};

struct sgx535_fixed_ops {
    int (*run)(void *context, enum sgx535_fixed_stage stage,
               const void *payload, size_t count,
               struct sgx535_fixed_observation *observation);
};

/* Passive trace of the most recently reached service point and first failure.
 * raw_result is the unmodified callback/status-source return when source is
 * BACKEND_CALLBACK or STATUS_SOURCE. observation_* copy values already
 * returned by the callback; no extra backend operation is performed. */
struct sgx535_fixed_diagnostic {
    enum sgx535_fixed_stage stage_reached;
    enum sgx535_fixed_stage failure_stage;
    enum sgx535_fixed_stage observation_stage;
    enum sgx535_fixed_failure_source failure_source;
    int raw_result;
    sgx535_u32 observation_load_flags;
    sgx535_u32 observation_status1;
    sgx535_u32 observation_status2;
    sgx535_u32 observation_initend;
};

/* A future live source must atomically associate and acknowledge selected
 * status for this scene. A raw register snapshot alone is not attribution. */
struct sgx535_fixed_status_source {
    int (*sample_and_ack)(void *context, sgx535_u32 sequence,
                          sgx535_u32 *status1, sgx535_u32 *status2,
                          int *exclusive_owned);
};

struct sgx535_fixed_service;
/* Optional passive evidence tap. It cannot alter the service result or drive
 * a backend operation. Default NULL preserves existing CPU harness behavior. */
struct sgx535_fixed_service_observer {
    void (*begin)(void *, struct sgx535_fixed_service *,
        const struct sgx535_fixed_ops *, const struct sgx535_fixed_status_source *, void *);
    void (*before)(void *, struct sgx535_fixed_service *, sgx535_u32,
        sgx535_u32, sgx535_u32, int);
    void (*after)(void *, struct sgx535_fixed_service *);
    void (*terminal)(void *, struct sgx535_fixed_service *, int);
};

struct sgx535_fixed_service {
    struct sgx535_frozen_session *session;
    struct sgx535_frozen_bo bos[SGX535_BO_COUNT];
    struct sgx535_frozen_command_pairs commands;
    struct sgx535_frozen_xhw_bind_fire_wire ta_wire;
    struct sgx535_frozen_xhw_bind_fire_wire raster_wire;
    struct sgx535_frozen_use_plan use_plan;
    struct sgx535_frozen_bootstrap boot;
    sgx535_u64 mmu_end;
    sgx535_u32 started;
    sgx535_u32 unsafe_possible;
    sgx535_u32 use_owned;
    struct sgx535_fixed_diagnostic diagnostic;
    const struct sgx535_fixed_service_observer *observer;
    void *observer_context;
};

int sgx535_fixed_service_bind(struct sgx535_fixed_service *service,
                              struct sgx535_frozen_session *session,
                              const struct sgx535_frozen_bo *bos,
                              size_t count, sgx535_u64 mmu_end,
                              const struct sgx535_frozen_command_pairs *commands);
int sgx535_fixed_service_prepare(struct sgx535_fixed_service *service,
                                  const struct sgx535_fixed_ops *ops,
                                  void *context, sgx535_u32 raw_revision);
int sgx535_fixed_service_fire_ta(struct sgx535_fixed_service *service,
                                  const struct sgx535_fixed_ops *ops,
                                  void *context, sgx535_u32 sequence,
                                  sgx535_u32 timeout_ticks);
int sgx535_fixed_service_status(struct sgx535_fixed_service *service,
                                 const struct sgx535_fixed_ops *ops,
                                 void *context, sgx535_u32 sequence,
                                 sgx535_u32 status1, sgx535_u32 status2,
                                 int exclusive_owned);
int sgx535_fixed_service_timeout(struct sgx535_fixed_service *service);
int sgx535_fixed_service_retire(struct sgx535_fixed_service *service,
                                 const struct sgx535_fixed_ops *ops,
                                 void *context);
int sgx535_fixed_service_may_release(
    const struct sgx535_fixed_service *service);
int sgx535_fixed_service_run_once(
    struct sgx535_fixed_service *service,
    const struct sgx535_fixed_ops *ops,
    const struct sgx535_fixed_status_source *source,
    void *context, sgx535_u32 raw_revision,
    sgx535_u32 sequence, sgx535_u32 timeout_ticks,
    sgx535_u32 max_samples);

#endif
